### ISSUE TITLE
Please remove the tracker!

### ISSUE THREAD

**Issue by realSNES** [KUN1007/kun-galgame-nuxt3#24] opened 2024-03-10 11:16 UTC
We found the following code snippet on [your website](https://www.kungal.com/)
``` html
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-82LF33PB7T"></script>
```
This is the Google Tag Manager, a web tracker that collaborates with Google Ads to facilitate ad tracking and logging.
Clearly, this contradicts the description in the README.md, which states:
``` markdown
### 3\. NO ADs Forever

Literally, **the website will never have any form of advertisements**. We believe a good forum should not have any advertising. If you find something resembling an ad, please report it. If 10 people report it, the topic will be locked.
```
To summarize, please remove the tracker!

**Comment by KUN1007** [comment] 2024-03-10 12:38
Thank you very much for your feedback.
However, after our investigation, we found that there is no such script on our website.
![image](https://github.com/KUN1007/kun-galgame-nuxt3/assets/89312077/a6935392-8056-4ca4-a34e-c43b0b8e4ba5)

We have never added such a package to the website code, and this is the first time we have heard of googletagmanager, and we have never used it.
![image](https://github.com/KUN1007/kun-galgame-nuxt3/assets/89312077/0e286d25-2da6-4459-9f18-ae150b834ca4)

We highly value your feedback, but as you can see, there are no ad placements on our website. If you can provide specific screenshots or code snippets, we will thoroughly investigate this issue.
We do not embed any advertisements on our website.

**Comment by realSNES** [comment] 2024-03-10 14:33
Although it doesn’t exist in the source code, it does exist in the actual production environment, as shown in the screenshot.

![Image_1710080804853](https://github.com/KUN1007/kun-galgame-nuxt3/assets/162039573/71a0855a-ddc4-48c0-93ba-f12045031865)


We suspect that you might be using a cloud service provided by Google, and that Google has automatically enabled it for you. For instance, Cloudflare, which my site uses, automatically enables a tracker for me to track users.

My suggestion is for you to check your server or your Google Cloud service.

This is an issue I’ve encountered on other people’s sites and even on my own.

**Comment by KUN1007** [comment] 2024-03-13 08:55
It has been three days, and we have not found any content related to googletagmanager on our website. Please provide additional clarification on this issue.
Based on our analysis, we suspect that this issue may be caused by a local browser plugin. Please ensure that your browser's debugging is in privacy mode when accessing the website.
If you do not provide any further information, we will abandon tracking this issue and close it after 30 days.

**Comment by KUN1007** [comment] 2024-04-13 17:29
No additional clarification provided, closed.

**Closed by KUN1007** 2024-04-13 17:29 UTC
Labels: bug, need more feedback
